In [2]:
# Imports and dependencies
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
from flask import Flask, jsonify, render_template
demo_data = pd.read_csv('Resources/Demographics.csv')
cause_data = pd.read_csv('Resources/Cause.csv')

In [3]:
cause_data

,Census Region Code,Year,UCD - Injury Intent,Injury Mechanism,Deaths,Population,Crude Rate
0,CENS-R1,1999,Suicide,Cut/Pierce,86,53343775,0.2
1,CENS-R1,1999,Suicide,Drowning,77,53343775,0.1
2,CENS-R1,1999,Suicide,Firearm,1808,53343775,3.4
3,CENS-R1,1999,Suicide,Poisoning,754,53343775,1.4
4,CENS-R1,1999,Suicide,Suffocation,1092,53343775,2
...,...,...,...,...,...,...,...
515,CENS-R4,2020,Suicide,Drowning,134,78654756,0.2
516,CENS-R4,2020,Suicide,Firearm,5880,78654756,7.5
517,CENS-R4,2020,Suicide,Poisoning,1553,78654756,2
518,CENS-R4,2020,Suicide,Suffocation,3358,78654756,4.3
519,CENS-R4,2020,Suicide,Unspecified Injury,20,78654756,0

In [4]:
demo_data_df = demo_data[["Year", "Census Region Code", "Age", "Race", "Deaths", "Population", "Crude Rate"]]
demo_data_df = demo_data_df.replace("Unreliable", "")
demo_data_df = demo_data_df.dropna(how='any')
demo_data_df

,Year,Census Region Code,Age,Race,Deaths,Population,Crude Rate
0,1999,CENS-R1,5-14 years,White,24,5894667,0.4
1,1999,CENS-R1,15-24 years,Asian or Pacific Islander,12,354327,
2,1999,CENS-R1,15-24 years,Black or African American,68,1046832,6.5
3,1999,CENS-R1,15-24 years,White,435,5398448,8.1
4,1999,CENS-R1,25-34 years,Asian or Pacific Islander,31,446429,6.9
...,...,...,...,...,...,...,...
2214,2020,CENS-R4,65-74 years,White,1188,6091864,19.5
2215,2020,CENS-R4,75-84 years,Asian or Pacific Islander,42,427127,9.8
2216,2020,CENS-R4,75-84 years,White,739,3052015,24.2
2217,2020,CENS-R4,85+ years,Asian or Pacific Islander,24,200037,12
2218,2020,CENS-R4,85+ years,White,373,1193796,31.2

In [5]:
## Create and clean dataframe to store cause of death data
cause_data_df = cause_data[["Year", "Census Region Code", "Injury Mechanism", "Deaths", "Population", "Crude Rate"]]
cause_data_df = cause_data_df.replace("Unreliable", "")
cause_data_df = cause_data_df.dropna(how='any')
cause_data_df

,Year,Census Region Code,Injury Mechanism,Deaths,Population,Crude Rate
0,1999,CENS-R1,Cut/Pierce,86,53343775,0.2
1,1999,CENS-R1,Drowning,77,53343775,0.1
2,1999,CENS-R1,Firearm,1808,53343775,3.4
3,1999,CENS-R1,Poisoning,754,53343775,1.4
4,1999,CENS-R1,Suffocation,1092,53343775,2
...,...,...,...,...,...,...
515,2020,CENS-R4,Drowning,134,78654756,0.2
516,2020,CENS-R4,Firearm,5880,78654756,7.5
517,2020,CENS-R4,Poisoning,1553,78654756,2
518,2020,CENS-R4,Suffocation,3358,78654756,4.3
519,2020,CENS-R4,Unspecified Injury,20,78654756,0

In [7]:
## Creating aggregate Demographic data that does removes the distinction of race
demo_data_agg_df = demo_data[["Year", "Census Region Code", "Age", "Deaths", "Population"]]
demo_data_agg_group = demo_data_agg_df.groupby(["Census Region Code", "Year"])
demo_data_agg_group_df = demo_data_agg_group.sum()
demo_data_agg_group_df["Crude Rate"] = ((demo_data_agg_group_df["Deaths"] / demo_data_agg_group_df["Population"]) * 100000)
demo_data_agg_group_df

                         Deaths  Population  Crude Rate
Census Region Code Year
CENS-R1            1999    4184    47853104    8.743424
                   2000    4133    47737123    8.657832
                   2001    4266    48364167    8.820580
                   2002    4235    48379506    8.753707
                   2003    4228    48851137    8.654865
...                         ...         ...         ...
CENS-R4            2016   11446    69286467   16.519821
                   2017   11963    71833777   16.653725
                   2018   12302    70971988   17.333599
                   2019   12360    71540498   17.276928
                   2020   11873    73267503   16.205002

[88 rows x 3 columns]

In [8]:
## Exporting dataframes as CSVs to then use in database loading
demo_data_df.to_csv("output/demographics.csv", index=False)
cause_data_df.to_csv("output/causes.csv", index=False)
demo_data_agg_group_df.to_csv("output/demographicsAggregate.csv", index=False)

In [50]:
## We can delete this cell if we decide we do not in fact need it
frames = [demo_data_df, cause_data_df]

result = pd.merge(demo_data_df, cause_data_df, how='right', on=['Year', 'Census Region Code'])

result

,Year,Census Region Code,Age,Race,Deaths_x,Population_x,Crude Rate_x,Injury Mechanism,Deaths_y,Population_y,Crude Rate_y
0,1999,CENS-R1,5-14 years,White,24,5894667,0.4,Cut/Pierce,86,53343775,0.2
1,1999,CENS-R1,15-24 years,Asian or Pacific Islander,12,354327,,Cut/Pierce,86,53343775,0.2
2,1999,CENS-R1,15-24 years,Black or African American,68,1046832,6.5,Cut/Pierce,86,53343775,0.2
3,1999,CENS-R1,15-24 years,White,435,5398448,8.1,Cut/Pierce,86,53343775,0.2
4,1999,CENS-R1,25-34 years,Asian or Pacific Islander,31,446429,6.9,Cut/Pierce,86,53343775,0.2
...,...,...,...,...,...,...,...,...,...,...,...
13097,2020,CENS-R4,65-74 years,White,1188,6091864,19.5,Unspecified Injury,20,78654756,0
13098,2020,CENS-R4,75-84 years,Asian or Pacific Islander,42,427127,9.8,Unspecified Injury,20,78654756,0
13099,2020,CENS-R4,75-84 years,White,739,3052015,24.2,Unspecified Injury,20,78654756,0
13100,2020,CENS-R4,85+ years,Asian or Pacific Islander,24,200037,12,Unspecified Injury,20,78654756,0
13101,2020,CENS-R4,85+ years,White,373,1193796,31.2,Unspecified Injury,20,78654756,0

In [53]:
## We can delete this cell if we decide we do not in fact need it
merged_1 = result.drop_duplicates(subset= ["Injury Mechanism", "Deaths_y", "Population_y", "Crude Rate_y"], keep = 'first')

In [56]:
## We can delete this cell if we decide we do not in fact need it
merged_1  = result.to_csv('merged1.csv', encoding ='utf-8')

In [ ]:
## Define and run engine for database loading
engine = create_engine(f"sqlite:///data/suicides.sqlite")
Base = automap_base()
Base.prepare(autoload_with=engine)
session = Session(engine)
connection = engine.connect()

In [ ]:
## Load dataframes into database
demo_data_df.to_sql("Demographics", connection, if_exists="replace")
cause_data_df.to_sql("Causes", connection, if_exists="replace")
demo_data_agg_group_df.to_sql("DemographicsAggregate", connection, if_exists="replace")